plugins: fromfilename chroma
directory: ~/Music
library: ~/Music/musiclibrary.db
art_filename: albumart
#threaded: yes
#original_date: no
per_disc_numbering: no

#convert:
#    auto: no
#    ffmpeg: /usr/bin/ffmpeg
#    opts: -ab 320k -ac 2 -ar 48000
#    max_bitrate: 320
#    threads: 1

paths:
    default: $albumartist/$album%aunique{}/$title
    singleton: $artist/$title
    comp: Compilations/$album%aunique{}/$title
    albumtype_soundtrack: Soundtracks/$album/$title

import:
    write: yes
    copy: yes
    move: no
#    resume: ask
#    incremental: yes
#    quiet_fallback: skip
    timid: yes
#    log: /config/beet.log
