useFractions = true
recipes_per_page = 12
rectree_hidden_columns = [ "Website", "Yield", "Yield Unit", "Preparation Time", "Cooking Time",]
showToolbar = true
readableUnits = true

[shopGuiWin]
window_size = [ 800, 600,]
position = [ 0, 0,]

[shopvpaned1]
position = 150

[shophpaned1]
position = 400

[rectree_column_order]

[sautTog]
active = false

[regexpTog]
active = false

[app_window]
window_size = [ 1334, 712,]
position = [ 13, 13,]

[reccard_window_1]
window_size = [ 654, 712,]
position = [ 693, 13,]
